### ISSUE TITLE
Including information on how to build all images for application

### ISSUE THREAD

**Issue by bkabrda** [projectatomic/nulecule#105]
## Background

I'm working on a tool called atomicapp-builder [1], that should be able to rebuild a whole Nulecule app based on a given Nulecule file and cccp-index [2].
## Terminology

While working on atomicapp-builder, I realized that Nulecule operates with two types of images, that don't really have names in Nulecule documentation (at least I didn't find the names :)). I'll call them **meta images** and **binary images** throughout this proposal:
- **meta image** is an image created from repo that contains a Nulecule file and perhaps some provider files (like k8s config etc); **meta image** doesn't contain any actual source code of the application
- **binary image** is an image that contains services needed to actually run the application, e.g. a database, a web server with application logic etc.
## Problem statement

While current Nulecule specification, combined with a cccp-index, allows resolving what **meta images** need to be built for an application to work, there is no general way to tell what **binary images** need to be built and how. This is problematic for my use case, since atomicapp-builder should be able to build all images from scratch.
## Proposal

I'd like to propose an addition of optional field called `images` for `graph` items. This field, if used, would provide information required to build **binary** images for the application. An example follows:

```
graph:
  - name: foobar
    params:
      - name: image
        description: The frontend part
        default: foobar:sometag
      - name: hostport
        description: The host TCP port as the external endpoint
        default: 80
      - name: publicip
        description: The IP address or addresses at which your app can be reached
    artifacts:
      kubernetes:
        - file://artifacts/k8s/foobar-controller.json
        - file://artifacts/k8s/foobar-service.json
    images:
      - name: foobar:sometag
        source: https://github.com/foo/bar/
        scm_type: git
        build_configs:
          stable:
            tag: v1.2.3
          latest:
            branch: master
        image_type: docker
        image_buildfile: some/dir/Dockerfile
```

I think the example is quite self-explanatory, so I'll just comment very briefly:
- `images` is a list of json objects with following properties:
  - `name` (required) - name of the image to build
  - `source` (required) - SCM repository URL
  - `scm_type` (optional) - type of SCM to use, defaults to `git`
  - `build_configs` (optional) - a json object containing named build configurations; only 2 configs are allowed - `stable` and `master`
    - every build config can contain either `branch` or `tag`; the default is `branch: master`
    - by default, both configs point to master branch, e.g.

```
latest:
  branch: master
stable:
  branch: master
```
- `branch` or `tag` (optional) - branch or tag to build from
- `image_type` (optional) - type of containerization engine to build image for, defaults to `docker`
- `image_buildfile` (optional) - path of build file of the image inside the repo, defaults to `Dockerfile`
## Things to consider / Q&A
- Q: What if user doesn't provide any/all instructions on how to build images?
  A: Since the field is optional, this is not a problem. Some tooling may however require providing list of all images that will be needed for the application; if an incomplete list is provided, this tooling may be unable to work with the application.
- Q: Why have multiple build configs?
  A: So that there is a builtin way to specify how to build various versions of this application, e.g. the latest development version, the latest stable version, a specific released version, etc... The tooling used for building Nulecule apps shall expose options to select one of the build configs.
- Q: Why not provide arbitrary number of configs?
  A: This crossed my mind, but I'm not sure how to sanely implement this in the build tooling. The problem is that the set of images to build is unknown prior to invoking the build, so a defined set of configurations makes sense (I can't specify configs for images that I don't know will be built). OTOH the problem is, that I may want to be building my app with `latest` config, but all its dependencies in `stable` config... I'm a bit torn here, another opinion would be appreciated!
- Q: Isn't this too complicated?
  A: I don't know, you tell me :) If someone can think of a nicer/more concise way, I'll be happy to see it!

CC @arrfab @vpavlin @kbsingh

[1] https://github.com/bkabrda/atomicapp-builder/
[2] https://github.com/kbsingh/cccp-index/
