### ISSUE TITLE
Adding a default provider [discussion]

### ISSUE THREAD

**Issue by cdrage** [projectatomic/nulecule#184]
Please read: https://github.com/projectatomic/atomicapp/issues/378

We would like to propose adding:

``` yaml
specversion: 0.0.2
id: guestbook-app

config:
  defaultprovider: docker
...
```

To the spec, giving an implementation control on what to deploy by default if multiple providers are provided.

**Comment by goern** [comment]
I would consider this an experimental extension: add it to the Nulecule files you use with current version of atomicapp and simply use it. For the Nulecule Spec's point of view, I think we dont need the semantic of a 'default provider'. 
If it turns out to be useful, lets move it from 'experimental' to be included in the Nulecule spec itself.

**Comment by aweiteka** [comment]
As an experimental extension I suggest it goes into the metadata section so it's still valid:

``` yaml
metadata:
  name: Hello Apache App
  appversion: 0.0.1
  description: Atomic app for deploying a really basic Apache HTTP server
  defaultprovider: docker
...
```
