### ISSUE TITLE
Adding a default namespace [discussion]

### ISSUE THREAD

**Issue by cdrage** [projectatomic/nulecule#185]
A problem that were facing is people whom are using inherited Nuleculized applications with the **Docker** provider (within our atomicapp python implementation) are facing namespace issues when deploying their packaged containers.

For example, when using `atomicapp run --provider=docker projectatomic/helloapache` you end up with a container named `atomicapp_default_HASHVALUE`. If you provide a namespace within an answers.conf file, you'll end up with `atomicapp_name_HASHVALUE` as the container name.

Due to the way that we package Nulecule applications, we do not actually provide a default namespace for the implementation to use, we rely on the user to pass in an answers.conf file.

I propose and would like to discuss the possibility of adding a `namespace` variable to the Nulecule file as a default name that is used when deploying. Thus having a default name when launching multiple inherited Nulecule containers. 

ex.

``` yaml
metadata:
  name: Hello Apache App
  namespace: helloapache
  appversion: 0.0.1
  description: Atomic app for deploying a really basic Apache HTTP server
```
