### ISSUE TITLE
Autogenerated Parameters

### ISSUE THREAD

**Issue by markllama** [projectatomic/nulecule#186]
As an atomicapp developer
I would like to be able to define some parameters which are autogenerated from a pattern
So that I can avoid having to provide values which are only used to connect two containers.

Use Case Example:

When creating internal only databases, the database server and consumer must agree on username/password or client/server certificates, but the precise values are unimportant because they are only used internally.  I would like to be able to have 

Nulecule specification change:

```
params:
  - name: dbuser
  - description: The name of the database read/write user
  - generate: "expression"
  - from: <RE pattern>
```
- _generate_ directive - indicate that this is a dynamically generated value
  
  This could be a time stamp, or an RE expression or a random number or some other dynamically
  created value type
  
  The first acceptable value would be "expression" but others are possible
-  _from_ directive
  
  With the "expression" value of the _from_ directive, this provides the pattern to use to produce a random value
