### ISSUE TITLE
Use list of apps instead of magic key naming

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/nulecule#35]
Looking at a [Kubernetes API issue](https://github.com/GoogleCloudPlatform/kubernetes/issues/2004) they point out the potential for confusion when using arbitrary names for keys. Consider A vs B:

A, current spec:

```
graph:
  mariadb-app:
    params:
      ...
    artifacts:
      ...
```

B, proposed

```
graph:
  - name: mariadb-app
    params:
      ...
    artifacts:
      ...
```

I think B is clearer that we're not doing something magic with the keys; They're just arbitrary names. Note we would have to bump the spec version with this change.

**Comment by vpavlin** [comment]
I guess this would be also case for params. Not sure if anything else carries same semantics, but I'd say components and params are the only ones we designed this way

**Comment by aweiteka** [comment]
As a user I was a bit confused about which key to use for params, so I agree. So if we have the same treatment for params...

```
graph:
  - name: mariadb-app
    params:
      - name: password
        description: db passphrase
      - name: image
        description: db image
        default: vpavlin/mariadb
    artifacts:
    ...
```
