### ISSUE TITLE
Expand artifacts source methods

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/nulecule#60]
We want to be able to use remote provider artifacts for several reasons:
- there are typically external sources for provider files (for example, [docker compose](https://github.com/stackforge/kolla/tree/master/compose), [kubernetes](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples))
- if remote sources exist we don't want to clone and maintain them separately
- remote source must be version controlled

Proposal by way of example:
1. Local file (current specification)
   
   ```
    artifacts:
     - file://path/to/local/file.json
   ```
2. Version control (support `branch` and `tag`)
   
   ```
   artifacts:
     - source: https://github.com/GoogleCloudPlatform/kubernetes.git
       type: git
       branch: release-0.9
       path: examples/guestbook
   ```
3. Single remote file
   
   ```
   artifacts:
     - https://raw.githubusercontent.com/projectatomic/nulecule/master/examples/helloapache/artifacts/k8s/hello-apache-pod.json
   ```

**Comment by aweiteka** [comment]
@tradej could you take a look at this?

**Comment by aweiteka** [comment]
Duplicate of https://github.com/projectatomic/nulecule/issues/37

**Comment by tradej** [comment]
I believe it's just a typo, but for clarity. For the single file (remote or local) It should be:

```
artifacts:
  kubernetes:
    - https://my.example.com:5555
```

and in a special case:

```
artifacts:
  kubernetes:
    - type: git
      url: https://github.com/GoogleCloudPlatform/kubernetes.git
      branch: release-0.9
      path: examples/guestbook
```

This allows for support of other versioning systems as well (Mercurial, CVS). Based on the `type`, the appropriate keys and values will be used by the library.
